var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['1. Welcome!', 'Welcome!.html',{'tt':'1. Welcome!','sb':'Welcome!.html'},
			['1.1 Countrywide discussion pro... ', 'Countrywidediscussionprocess.html',{'tt':'1.1 Countrywide discussion process','sb':'Countrywidediscussionprocess.html'},],
			['1.2 Our country in seven point... ', 'Ourcountryinsevenpoints.html',{'tt':'1.2 Our country in seven points','sb':'Ourcountryinsevenpoints.html'},],
			['1.3 Hinterland Forward!', 'HinterlandForward!.html',{'tt':'1.3 Hinterland Forward!','sb':'HinterlandForward!.html'},],
],
		['2. Our goals', 'Ourgoals.html',{'tt':'2. Our goals','sb':'Ourgoals.html'},
			['2.1 Sustainable Development Go... ', 'SustainableDevelopmentGoals.html',{'tt':'2.1 Sustainable Development Goals','sb':'SustainableDevelopmentGoals.html'},],
			['2.2 SDG 3: Ensure healthy live... ', 'SDG3.Ensurehealthylivesandpromotewellbei.html',{'tt':'2.2 SDG 3: Ensure healthy lives and promote wellbeing for all at all ages','sb':'SDG3.Ensurehealthylivesandpromotewellbei.html'},],
			['2.3 SDG 4: Ensure inclusive an... ', 'SDG4.Ensureinclusiveandequitablequalitye.html',{'tt':'2.3 SDG 4: Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all','sb':'SDG4.Ensureinclusiveandequitablequalitye.html'},],
			['2.4 SDG 7: Ensure access to af... ', 'SDG7.Ensureaccesstoaffordable\,reliable\,s.html',{'tt':'2.4 SDG 7: Ensure access to affordable\, reliable\, sustainable and modern energy for all','sb':'SDG7.Ensureaccesstoaffordable\,reliable\,s.html'},],
			['2.5 SDG 9: Build resilient inf... ', 'SDG9.Buildresilientinfrastructure\,promot.html',{'tt':'2.5 SDG 9: Build resilient infrastructure\, promote inclusive and sustainable industrialisation\, and foster innovation','sb':'SDG9.Buildresilientinfrastructure\,promot.html'},],
			['2.6 SDG 10: Reduce inequality ... ', 'SDG10.Reduceinequalitywithinandamongcoun.html',{'tt':'2.6 SDG 10: Reduce inequality within and among countries','sb':'SDG10.Reduceinequalitywithinandamongcoun.html'},],
],
		['3. Our program', 'Ourprogram.html',{'tt':'3. Our program','sb':'Ourprogram.html'},
			['3.1 The telecom track', 'Thetelecomtrack.html',{'tt':'3.1 The telecom track','sb':'Thetelecomtrack.html'},],
			['3.2 The electricity track', 'Theelectricitytrack.html',{'tt':'3.2 The electricity track','sb':'Theelectricitytrack.html'},],
			['3.3 The premises track', 'Thepremisestrack.html',{'tt':'3.3 The premises track','sb':'Thepremisestrack.html'},],
			['3.4 The organization track', 'Theorganizationtrack.html',{'tt':'3.4 The organization track','sb':'Theorganizationtrack.html'},],
			['3.5 Management', 'Management.html',{'tt':'3.5 Management','sb':'Management.html'},],
],
		['4. Our financing', 'Ourfinancing.html',{'tt':'4. Our financing','sb':'Ourfinancing.html'},
			['4.1 Role of Multilateral Devel... ', 'RoleofMultilateralDevelopmentBanks.html',{'tt':'4.1 Role of Multilateral Development Banks','sb':'RoleofMultilateralDevelopmentBanks.html'},],
			['4.2 Financing the telecom trac... ', 'Financingthetelecomtrack.html',{'tt':'4.2 Financing the telecom track','sb':'Financingthetelecomtrack.html'},],
			['4.3 Funding the electricity tr... ', 'Fundingtheelectricitytrack.html',{'tt':'4.3 Funding the electricity track','sb':'Fundingtheelectricitytrack.html'},],
			['4.4 Funding the premises track', 'Fundingthepremisestrack.html',{'tt':'4.4 Funding the premises track','sb':'Fundingthepremisestrack.html'},],
			['4.5 Funding the organization t... ', 'Fundingtheorganizationtrack.html',{'tt':'4.5 Funding the organization track','sb':'Fundingtheorganizationtrack.html'},],
			['4.6 Funding program management... ', 'Fundingprogrammanagementandfundingoperat.html',{'tt':'4.6 Funding program management and funding operations','sb':'Fundingprogrammanagementandfundingoperat.html'},],
],

]
];